### ISSUE TITLE
How to use files2rouge on Chinese words

### ISSUE THREAD

**Issue by travel-go** [pltrdy/files2rouge#23]
Hello.:
When I use LCSTS data ,I also use file2rouge script to evaluate. However, I find the score is low. I would like to ask how to use file2rouge script to measure Chinese data.
 
I hope for your reply.

**Comment by KelleyYin** [comment]
Good question

**Comment by jufengada** [comment]
Good question!

**Comment by pltrdy** [comment]
ROUGE algorithm compares an hypothesis sequence with a reference based on word match. You should have one hypothesis, and one reference file with 1 sequence per line. Words are sequences of characters separated  by space. 

It should word with any language, and any kind of UTF-8 chars, therefore, Chinese shouldn't be a problem. Try to find examples that you are sure to be erroneous.

**Comment by pltrdy** [comment]
If each Chinese characters are separated by space they will be considered separate words. Otherwise it would be seen as letters, so what you say make sense (at least with respect to the specifications). 

I don't know what's the standard for chinese scoring

**Comment by travel-go** [comment]
@pltrdy Thank you. I wonder if it is correct to map Chinese characters to numbers through the global vocabulary. Are there any problems with the scores obtained after doing so?

**Comment by pltrdy** [comment]
Replacing characters to numbers is exactly like considering each character as a word, therefore the result with be based on character match. I'm not sure how relevant it is for Chinese.

**Comment by travel-go** [comment]
Thank you.

**Comment by jufengada** [comment]
> Thank you.

If you find the good way to calculate the rouge of Chinese?

**Comment by travel-go** [comment]
I use the above answer method

**Comment by jufengada** [comment]
thanks!
