### ISSUE TITLE
Problem with OOV words (do not use `<unk>` or anything with a `<`)

### ISSUE THREAD

**Issue by downloaderga** [pltrdy/files2rouge#24]
Can anyone tell me, why i received 2 different rouge scores when:
+ Both summary and reference used `<unk>` for OOV words
+ Both summary and reference used `UNK` for OOV words

For example, a piece of Gigaword:
**summary file (summary.txt):**
> nec UNK computer to join forces
sri lanka closes schools schools
five anti-nuclear protesters arrested
factory orders up #.# percent in september
bank of tokyo urges calm after us decision
croatia croatia agree to meet saturday
toyota banned from world rally championship
israel prepares for rabin 's state funeral
indian pm 's promise of more autonomy for kashmir
UNK UNK UNK UNK
turnout heavy for trinidad and tobago
jordan 's crown prince hassan visits jerusalem
poland 's main opposition party endorses walesa
rand gains against dollar
amnesty international condemns guinea arrests
syrian woman arrested in turkey on terrorism charges
hong kong us sign air agreement
us citizen given suspended sentence for spying
love leads world cup of golf
france names team for second test

**reference file (reference.txt)**
> nec UNK in computer sales tie-up
sri lanka closes schools as war escalates
protesters target french research ship
us september factory orders up #.# percent
bank of UNK UNK for calm in financial markets
rebel serb talks to resume saturday : tudjman by peter UNK 
toyota are banned for a year
israel prepares jerusalem state funeral for rabin
indian pm 's announcement on kashmir polls autonomy sparks outrage
russian liberal party wins registration
trinidad and tobago poll draws heavy turnout by john babb
jordan 's crown prince makes first visit to jerusalem
walesa receives opposition boost
rand gains ground
amnesty deplores human rights violations in guinea
canada investigates syrian woman with alleged ties to pkk
hong kong us sign breakthrough aviation pact
us citizen who spied for east germans given suspended sentence
americans lead UNK by ## strokes
french keep same team for #nd test

with command: `files2rouge summary.txt reference.txt`, rouge scores are:

> 1 ROUGE-1 Average_R: 0.44461 (95%-conf.int. 0.34635 - 0.54301)
> 1 ROUGE-1 Average_P: 0.50481 (95%-conf.int. 0.38311 - 0.61899)
> 1 ROUGE-1 Average_F: 0.46588 (95%-conf.int. 0.36164 - 0.56812)
> 
> 1 ROUGE-2 Average_R: 0.21717 (95%-conf.int. 0.12431 - 0.31208)
> 1 ROUGE-2 Average_P: 0.25701 (95%-conf.int. 0.14881 - 0.37060)
> 1 ROUGE-2 Average_F: 0.23201 (95%-conf.int. 0.13381 - 0.33325)
> 
> 1 ROUGE-L Average_R: 0.39034 (95%-conf.int. 0.30762 - 0.47060)
> 1 ROUGE-L Average_P: 0.44722 (95%-conf.int. 0.34667 - 0.55026)
> 1 ROUGE-L Average_F: 0.41168 (95%-conf.int. 0.31882 - 0.49881)

But when I replaced all `UNK` by `<unk>` in both files, run with the same command: `files2rouge summary.txt reference.txt`, rouge scores are:

> 1 ROUGE-1 Average_R: 0.52403 (95%-conf.int. 0.40460 - 0.63460)
> 1 ROUGE-1 Average_P: 0.52284 (95%-conf.int. 0.39659 - 0.64956)
> 1 ROUGE-1 Average_F: 0.49917 (95%-conf.int. 0.38423 - 0.60513)
> 
> 1 ROUGE-2 Average_R: 0.25412 (95%-conf.int. 0.14458 - 0.38097)
> 1 ROUGE-2 Average_P: 0.24722 (95%-conf.int. 0.13810 - 0.36190)
> 1 ROUGE-2 Average_F: 0.22912 (95%-conf.int. 0.13134 - 0.33379)
> 
> 1 ROUGE-L Average_R: 0.46976 (95%-conf.int. 0.35841 - 0.57774)
> 1 ROUGE-L Average_P: 0.46525 (95%-conf.int. 0.34667 - 0.57706)
> 1 ROUGE-L Average_F: 0.44497 (95%-conf.int. 0.34012 - 0.54241)

**Comment by pltrdy** [comment]
Hi,

Thanks for reporting it. All I can say for now is that this isn't any kind of know issue/behavior.

It seems like the `<` is interpreted, somewhere, i.e. i tried multiple replacement for `UNK`, it turns out things are weird when `<` comes in (even when alone, i.e. `sed 's/UNK/</g`).

Use any token without `<`.

You should only take the scoring with `UNK` into account.
