### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'log_level'

### ISSUE THREAD

**Issue by jufengada** [pltrdy/files2rouge#25]
tengweideMacBook-Pro:files2rouge tengwei$ files2rouge result.txt valid.title.filter.txt
Preparing documents...
Running ROUGE...
Traceback (most recent call last):
  File "/anaconda/bin/files2rouge", line 11, in <module>
    load_entry_point('files2rouge==2.0.0', 'console_scripts', 'files2rouge')()
  File "/anaconda/lib/python3.5/site-packages/files2rouge-2.0.0-py3.5.egg/files2rouge/files2rouge.py", line 65, in main
    log_level=log_level)
TypeError: __init__() got an unexpected keyword argument 'log_level'

excuse me, I was successful running the files2rouge before. But this time I meet some issues. I don't know how to solve this problem, can you help me? Look forward to your reply. thanx!

**Comment by pltrdy** [comment]
Try to pull last code and install from sources 

(https://github.com/pltrdy/files2rouge/issues/8)

**Comment by jufengada** [comment]
thank you! I try it.
