### ISSUE TITLE
How much time is needed?

### ISSUE THREAD

**Issue by zm379096736** [pltrdy/files2rouge#27]
I tried to compare two files with it, but there was no result in one afternoon. The file had 140,000 lines. How long does it take me?

Thanks in advance

**Comment by pltrdy** [comment]
`ROUGE-L` calculation is quite expensive and it get worse if sequences are long (i.e. high `#n_words / #n_lines`).

It tooks `132.045 seconds` to process 11,490 lines w/ ~50 words in it (running on i7-6700K).
