### ISSUE TITLE
Problem while running setup_rouge.py

### ISSUE THREAD

**Issue by nouhadamak** [pltrdy/files2rouge#29]
cloud-miracl@Cloud-Miracl:~/Bureau/Nouha/Projects/files2rouge$ python setup_rouge.py
files2rouge uses scripts and tools that will not be stored with the python package
where do you want to save it? [default: /home/cloud-miracl/.files2rouge/]/home/cloud-miracl/usr/local/anaconda/lib/python3.6/site-packages/files2rouge-2.0.0-py3.6.egg/files2rouge 
Copying './files2rouge/RELEASE-1.5.5/' to '/home/cloud-miracl/usr/local/anaconda/lib/python3.6/site-packages/files2rouge-2.0.0-py3.6.egg/files2rouge'
Traceback (most recent call last):
  File "setup_rouge.py", line 40, in <module>
    data = copy_rouge()
  File "setup_rouge.py", line 33, in copy_rouge
    shutil.copytree(src_rouge_root, path)
  File "/home/cloud-miracl/usr/local/anaconda/lib/python3.6/shutil.py", line 315, in copytree
    os.makedirs(dst)
  File "/home/cloud-miracl/usr/local/anaconda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/cloud-miracl/usr/local/anaconda/lib/python3.6/site-packages/files2rouge-2.0.0-py3.6.egg/files2rouge'

**Comment by pltrdy** [comment]
`shutil.copytree` actually tries to create a new directory, the path you're passing already exists, which raises an error.
