### ISSUE TITLE
Problem with stemming

### ISSUE THREAD

**Issue by moussaKam** [pltrdy/files2rouge#34]
Hi, 
I am trying to perform the stemming before computing the statistics. I added -m option in the args however I'm getting the same scores as without it.

**Comment by jxhe** [comment]
That's because `pyrouge` sets stemming as True by default, but `files2rouge` updates this with https://github.com/pltrdy/files2rouge/commit/e39d882f489a56c8cf80511f8610636d6bbb5d36, you can try installing the latest `files2rouge` to obtain non-stemming results.
