### ISSUE TITLE
Inconsistent Behavior after Recent Update: Default Value of Stemming Option

### ISSUE THREAD

**Issue by jxhe** [pltrdy/files2rouge#37]
`files2rouge` was using stemming by default before the recent commit https://github.com/pltrdy/files2rouge/commit/e39d882f489a56c8cf80511f8610636d6bbb5d36 because `pyrouge` sets stemming as True by default. However the stemming option is default by False now, which causes the ROUGE scores obtained by standard command `files2rouge file1 file2` is not comparable to those obtained by `pyrouge` or the previous `files2rouge`, sometimes there is a large gap (over 1 point on R1 in my case).

This causes non-trivial trouble for us to reproduce other's results because many papers use either  `pyrouge` or the previous `files2rouge` to compute ROUGE scores. I appreciate the update to make `stemming` controllable, but I think the behavior of `files2rouge` should be ideally consistent with before, or at least mention this change in the README, otherwise it is difficult for us to realize that the current `files2rouge` command is actually different from the `file2rouge` used by other papers published before the recent update (by default).

**Comment by pltrdy** [comment]
That's a relevant concern, thanks for pointing this out. 

We could invert the flag i.e. use stemming by default and expose a "no stemming" option.
