### ISSUE TITLE
Incorrect Order of Reference and Summary in Readme

### ISSUE THREAD

**Issue by jxhe** [pltrdy/files2rouge#38]
I think the current code takes reference as the first argument while the summary is the second, thus README may need to be updated

**Comment by pltrdy** [comment]
It has been fixed in https://github.com/pltrdy/files2rouge/pull/36

**Comment by jxhe** [comment]
I mean the command line usage takes reference as the first argument while readme says the second, I don't think #36 fixed this, no?

**Comment by pltrdy** [comment]
Correct, my bad.

**Comment by memray** [comment]
Also this warning message in [utils.py] L42 (https://github.com/pltrdy/files2rouge/blob/e70ffa1661c7c11a54906de8c0c30fb0fd6d8947/files2rouge/utils.py#L42). Should it be "Empty reference at line %d." rather than "hypothesis"?

Thanks,
Rui

**Comment by pltrdy** [comment]
Hmm what makes you think it should be reference?
This line seems really about hypothesis (aka. model)

**Comment by memray** [comment]
I might have been confused by the naming. 
In its [caller](https://github.com/pltrdy/files2rouge/blob/e70ffa1661c7c11a54906de8c0c30fb0fd6d8947/files2rouge/files2rouge.py#L44), _ref_path_ (which I believe is the reference/groundtruth file?) is passed as argument _model_file_. Correct me if I'm wrong.

**Comment by pltrdy** [comment]
Oh no you are correct in fact. I don't like ROUGE terms "system" and "model" since I find it confusing (and was actually confused in last comment).

In fact, in ROUGE terms, "model" = "reference" i.e. gold summaries you evaluate against while "system" = "hypothesis" i.e. the summary generated.
The code is wrong, you're right.

**Comment by memray** [comment]
@pltrdy No problem and thanks very much for the confirmation! 
It is very confusing but your code comments really help.

**Comment by pltrdy** [comment]
@memray this will be fixed in the following PR, thx for raising it.
