### ISSUE TITLE
Problem with Average_F

### ISSUE THREAD

**Issue by senchfu** [pltrdy/files2rouge#42]
Hello, it seems the Average_F is not F1 score, for example

> 1 ROUGE-1 Average_R: 0.28242 (95%-conf.int. 0.25721 - 0.30877)
1 ROUGE-1 Average_P: 0.30157 (95%-conf.int. 0.27114 - 0.33506)
1 ROUGE-1 Average_F: 0.28196 (95%-conf.int. 0.25704 - 0.30722)

R=0.282, P=0.302, and F1 should be 2\*P\*R/(P+R)=0.292, is this know's issue or I made some wrong?

Thanks!

**Comment by pltrdy** [comment]
The results you see are averages. `F = 2*P*R/(P+R)` (for each evaluation) does not mean that `avg(F)=2*avg(P)*avg(R)/(avg(P)+avg(R))`
