### ISSUE TITLE
setup_rouge.py does not work with Python 3

### ISSUE THREAD

**Issue by da03** [pltrdy/files2rouge#5]
On python 3.5:
python setup_rouge.py 
files2rouge uses scripts and tools that will not be stored with the python package
Traceback (most recent call last):
  File "setup_rouge.py", line 37, in <module>
    data = copy_ROUGE()
  File "setup_rouge.py", line 20, in copy_ROUGE
    path = raw_input("where do you want to save it? [default: %s]" % default_root)
NameError: name 'raw_input' is not defined

**Comment by pltrdy** [comment]
Thanks for the issue. I was using a python 2 function, it must be fixed now.

**Comment by da03** [comment]
Thanks!
