### ISSUE TITLE
rouge-su

### ISSUE THREAD

**Issue by z1084307384** [pltrdy/files2rouge#54]
Hi,
I want to use rouge-su metric to evaluate my results , can this script compute rouge-su?

Thanks

**Comment by pltrdy** [comment]
Sorry for this --very-- late reply. 

`ROUGE` is initially a Perl script. This python package is a wrapper around the original script. Using this package, you can set your own set of arguments that will be used during `ROUGE` call.

This means you should refer at ROUGE docs i.e. [ROUGE/README.txt](https://github.com/pltrdy/files2rouge/blob/master/files2rouge/RELEASE-1.5.5/README.txt) and in particuliar  [the set of options](https://github.com/pltrdy/files2rouge/blob/master/files2rouge/RELEASE-1.5.5/README.txt#L125) and [line 174 that mention -U](https://github.com/pltrdy/files2rouge/blob/master/files2rouge/RELEASE-1.5.5/README.txt#L174)
