### ISSUE TITLE
ValueError: Model and System line counts must match, 196 != 1512

### ISSUE THREAD

**Issue by flore-xu** [pltrdy/files2rouge#55]
My `hyps.txt` and `refs.txt` each has 200 sentences, and each sentence contains lots of dot `'.'` and ends up by `'\n'`.

When I ran `files2rouge hyps.txt refs.txt`, it gives me `ValueError: Model and System line counts must match, 196 != 1512`

so I tried to change EOS sign from dot `'.'` to `'\n'` by enter `files2rouge hyps.txt refs.txt -e '\n'` or `files2rouge hyps.txt refs.txt --eos '\n'`, both commands didn't work and gave me the same error `ValueError: Model and System line counts must match, 196 != 1512`.

I wonder if I entered the wrong commands or if it's because other issues in my text files? Any help would be greatly appreciated!

**Comment by pltrdy** [comment]
Sorry for very late answers.

This error is about *line* count, not sentences. 
So in particular, it is expected that `wc -l hyps.txt` equals `wc -l refs.txt`
