### ISSUE TITLE
"eos" use?

### ISSUE THREAD

**Issue by FutureWithoutEnding** [pltrdy/files2rouge#57]
https://github.com/pltrdy/files2rouge/blob/d3d09c8387416e80353e3a01e959bf8cc1747f58/files2rouge/utils.py#L36
Why add a space before `eos`?

**Comment by pltrdy** [comment]
The point, i supposed, is to keep word separated from the eos token, that might be right next to another word. ie. with `eos='</s>'`, `hello world</s>` become `hello world </s>`

**Comment by FutureWithoutEnding** [comment]
```
>>> eos='</s>'
>>> line = "hello world</s>"
>>> (" %s\n" % eos).join(line.split(" %s" % eos))
'hello world</s>'
```
is `hello world</s>` not `hello world </s>`
