### ISSUE TITLE
TypeError: unexpected keyword argument 'log_level'

### ISSUE THREAD

**Issue by WenTsai** [pltrdy/files2rouge#7]
hello there,
I just tried to use this, but got the following error messages

```
Preparing documents...
Running ROUGE...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/files2rouge", line 9, in <module>
    load_entry_point('files2rouge==2.0.0', 'console_scripts', 'files2rouge')()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/files2rouge-2.0.0-py3.5.egg/files2rouge/files2rouge.py", line 65, in main
    log_level=log_level)
TypeError: __init__() got an unexpected keyword argument 'log_level'
```

Is there any idea to solve this?

Thanks.

**Comment by pltrdy** [comment]
This error is raised by the `__init__` of `pyrouge`, so I guess there's an issue with your version of `pyrouge`.

More specifically, I'm using https://github.com/bheinzerling/pyrouge, which in fact, has a `log_level` argument since [Nov, 2016](https://github.com/bheinzerling/pyrouge/commit/5aad794b0b394b63cd9fc4d86b4813da1fc8366a).

Could you check what `pyrouge` module do you have? or run `pip install pyrouge --upgrade`

**Comment by WenTsai** [comment]
The version of `pyrouge` is already latest both in python2 and python3.
```
pip2 install pyrouge --upgrade
Requirement already up-to-date: pyrouge in /Library/Python/2.7/site-packages

pip3 install pyrouge --upgrade
Requirement already up-to-date: pyrouge in /Library/Frameworks/Python.framework/
```

I'm not sure if this matter that I have both python2 and python3 in my computer. 
I used `python3` instead of the guideline in `README.md`.
(I got an `SyntaxError: invalid syntax` at print(), so I assumed that I have to use `python3` here.)

Thanks for your help.

**Comment by pltrdy** [comment]
Hmm true. I'm (over) assuming that `python` is a `python 3.x`. 

Maybe it's not the same module. I mean, you can download/clone any project that defines a `pyrouge` module and run `pip install .`.

Do you remember how you initially installed it?

**Comment by WenTsai** [comment]
I've finally solved this problem. So here goes some notes in case someone may have similar issues when using `files2rouge`.

## Check `pyrouge`
As @pltrdy mentioned, the main problem occurred from `pyrouge`. So before using `files2rouge`, I checked if my `pyrouge` can work or not.

An easy way to test if everything installed successfully:
(I have python2 and python3 on my computer, so I'm using python3 to make sure it works for python3.)
```
python3 -m pyrouge.test
```

There would be an **OK** after running the test, or it would show **FAILED** with some error.

## Uninstall `pyrouge`
To make everything working normally, I uninstalled the package and install it again.
```
pip2 uninstall pyrouge
pip3 uninstall pyrouge
```

## Install `pyrouge`
I cloned it for the latest version from github.
```
git clone https://github.com/bheinzerling/pyrouge
cd pyrouge
python3 setup.py install
```
After installation, I have to setup the path for `Rouge 1.5.5`, [which can be found here](https://github.com/andersjo/pyrouge/tree/master/tools/ROUGE-1.5.5).

According to the tutorial [here](https://stackoverflow.com/questions/47045436/how-to-install-the-python-package-pyrouge-on-microsoft-windows/47045437#47045437):

```
pyrouge_set_rouge_path /some-dir/pyrouge-master/tools/ROUGE-1.5.5 
```

I got an **OK** after running `python3 -m pyrouge.test` by those steps.

## Using `files2rouge`
 
I thought it could be executed successfully, but it still showed errors like `Cannot open exception db file for reading: data/WordNet-2.0.exc.db"`.

Fortunately, I found solution [here](https://github.com/masters-info-nantes/ter-resume-auto/blob/master/README.md):
```
cd data/WordNet-2.0-Exceptions/
rm WordNet-2.0.exc.db # only if exist
./buildExeptionDB.pl . exc WordNet-2.0.exc.db

cd ../
rm WordNet-2.0.exc.db # only if exist
ln -s WordNet-2.0-Exceptions/WordNet-2.0.exc.db WordNet-2.0.exc.db
```

Finally the `files2rouge` works!

Thanks a lot!

**Comment by pltrdy** [comment]
Thanks for sharing!

**Comment by hjs3545** [comment]
> I actually got the same error. I used `pip install pyrouge` (tried both on windows and Linux) and installed `pyrouge` version 0.1.3. It seems `log_level` as an input for `Rouge155()` was added after the package was released on `pip`, and it was not updated there. But I found it actually only being a small change by checking the page: [https://github.com/bheinzerling/pyrouge/commit/5aad794b0b394b63cd9fc4d86b4813da1fc8366a](url) So you could easily modify the `pyrouge` package code as instructed above.
> 
> Or, you could simply edit the `files2rouge.py` file (before running the setup files, otherwise you'll need to find and edit the copy created in your python library path), by commenting out the second input `log_level` (line 65) when initializing the `Rouge155` instance.
> 
> I checked and they both worked.

Hi, there.
Appreciate your answer but I have a question.
The link was vanished. How can i do that?
Thank you.

[https://github.com/bheinzerling/pyrouge/commit/5aad794b0b394b63cd9fc4d86b4813da1fc8366a](https://github.com/pltrdy/files2rouge/issues/url)
