### ISSUE TITLE
Unexpected keyword argument 'log_level'

### ISSUE THREAD

**Issue by cgebe** [pltrdy/files2rouge#8]
The `log_level` argument passed to pyrouge.Rouge155 is denied as unexpected argument:

```
Preparing documents...
Running ROUGE...
Traceback (most recent call last):
  File "/usr/local/bin/files2rouge", line 11, in <module>
    load_entry_point('files2rouge==2.0.0', 'console_scripts', 'files2rouge')()
  File "/usr/local/lib/python3.6/site-packages/files2rouge-2.0.0-py3.6.egg/files2rouge/files2rouge.py", line 65, in main
    log_level=log_level)
TypeError: __init__() got an unexpected keyword argument 'log_level'
```

Python: Version 3.6

**Comment by pltrdy** [comment]
The problem with `log_level` is not how to dodge it, but why it happens. I mean, current `pyrouge` code has such a parameter (see: https://github.com/bheinzerling/pyrouge/blob/master/pyrouge/Rouge155.py#L74) therefore it must not be a problem.

I do not care that much about this param, it just shows that you are not running the expected pyrouge code.

**Comment by cgebe** [comment]
59ad4b0c1c1c0ce9bbf7ee5a757a733940816898
